### ISSUE TITLE
Does not compile with glibc >= 2.28

### ISSUE THREAD

**Issue by blackPantherOS** [rrthomas/recode#11]
Changes in glibc 2.28 will breaks this application build,

> make  all-recursive
> make[3]: Entering directory '/usr/src/RPM/BUILD/recode-3.7/lib'
> make[4]: Entering directory '/usr/src/RPM/BUILD/recode-3.7/lib'
> /bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..     -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -D_REENTRANT -fPIC -MT fseterr.lo -MD -MP -MF .deps/fseterr.Tpo -c -o fseterr.lo fseterr.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -D_REENTRANT -fPIC -MT fseterr.lo -MD -MP -MF .deps/fseterr.Tpo -c fseterr.c  -fPIC -DPIC -o .libs/fseterr.o
> fseterr.c: In function ‘fseterr’:
> fseterr.c:78:3: error: #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
>   #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."
>    ^~~~~

**Comment by rrthomas** [comment]
Thanks for the heads up. The fix is to update gnulib. I will make a new source release with updated gnulib.

**Comment by rrthomas** [comment]
I've just pushed an update to gnulib that should fix this.

Could you possibly build from git to check that it does?

**Comment by blackPantherOS** [comment]
I will check today, thank you

**Comment by blackPantherOS** [comment]
Okay now, the build is working fine new updated gnulib.
